jtwsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls")), #경로 설정
]

users/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static 
from django.conf import settings
app_name = 'user'

urlpatterns = [
    path("login", views.login_view, name = 'login'), # login path 설정
    path("logout", views.logout_view, name = 'logout'), # logout path 설정
    path("signup", views.signup_view, name = 'signup'), # signup path 설정
    path("Chubu/Nagoya", views.GetNagoya, name = 'Nagoya'), # l
    path("Chubu/Takayama", views.GetTakayama, name = 'Takayama'), # l
    path("Chubu/Takayama_mov", views.GetTakayama_mov, name = 'Takayama_mov'),
    path("Chubu/Toyama", views.GetToyama, name = 'Toyama'), # 
    path("Chubu/Gero", views.GetGero, name = 'Gero'), # 
    path("Chubu/Shirakawago", views.GetShirakawago, name = 'Shirakawago'),
    path("login", views.GetBacktoLogin, name = 'GetBacktoLogin'), # 
    path("Chubu", views.Chubu_view, name = 'Chubu'), # jubu path 설정
    path("Wrong", views.Wrong_view, name="Wrong"),# 주부말고 다른거누를때
    path("Chubu/choice", views.choice_view, name="choice"),
    path("Chubu/choice_gero", views.choice_gero_view, name="choice_gero"),
    path("Chubu/choice_toyama", views.choice_toyama_view, name="choice_toyama"),
    path("Chubu/choice_nagoya", views.choice_nagoya_view, name="choice_nagoya"),
    path("Chubu/choice_shirakawago", views.choice_shirakawago_view, name="choice_shirakawago"),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser): #상속 받아 사용
    student_id = models.CharField(max_length=10) # student_id만 따로 추가 정의 

class blogdb(models.Model):
    title = models.CharField(max_length=20)
    content = models.CharField(max_length=100)

class picture_db(models.Model):
    address = models.CharField(max_length=100)
    location = models.CharField(max_length=20)
    etc1 = models.CharField(max_length=100)
    etc2 = models.CharField(max_length=100)
    etc3 = models.CharField(max_length=100)
class image_db(models.Model):
    title = models.CharField(max_length=20)
    content = models.CharField(max_length=100)
    
    

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib import messages
from .models import User
from .models import picture_db, image_db
import time
from django.db import connection
from django.shortcuts import render

import logging
logger = logging.getLogger('my')
logger2 = logging.getLogger('my2')
# Create your views here.
login_user_name = 'None'

def login_view(request):
    global login_user_name
    logger.info("LOAD LOGIN PAGE")
    msg = "_"
    if request.method == "POST":
#        print(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        
        login_user_name = username
        user = authenticate(username = username, password = password)
        if user is not None:
            print("인증성공")
            msg = "로그인성공"
            logger.info("USER:%s LOGIN SUCCESSED", login_user_name)
            login(request, user)
        else:
            print("인증실패")
            logger.info("USER:%s LOGIN FAILED", login_user_name)
            messages.info(request, "입력이 잘못되었습니다.")
            msg = "입력실패"
            
    return render(request, "users/login2.html",{'msg':msg})#20230312김정현

def logout_view(request):
    logger.info("LOAD LOGOUT PAGE")
    logout(request)
    logger.info("USER:%s LOGOUT SUCCESSED", login_user_name)
    return redirect("user:login")

def signup_view(request):
    global login_user_name
    logger.info("LOAD SIGNUP PAGE")
    msg = "_"
    if request.method == "POST":
        username =request.POST["username"]
        password =request.POST["password"]
        firstname =request.POST["firstname"]
        lastname =request.POST["lastname"]
        email =request.POST["email"]
        student_id =request.POST["student_id"]
        login_user_name = username
        if len(username)*len(password)*len(firstname)*len(lastname)*len(email)*len(student_id) != 0: 
            print(request.POST)
            user = User.objects.create_user(username, email, password)
            user.last_name = lastname
            user.first_name = firstname
            user.student_id = student_id
            user.save()
            logger.info("USER:%s SIGNUP SUCCESSED", login_user_name)
            return redirect("user:login")
        else:
            print("빈칸오류")
            msg = "빈칸을 모두 채워주세요"
            logger.info("USER:%s SIGNUP FAILED", login_user_name)
            # messages.info(request, "빈칸을 모두 채워주세요")
    return render(request, "users/signup.html",{'msg':msg})

def GetNagoya(request):
    logger.info("USER:%s LOAD NAGOYA PAGE", login_user_name)
    #print(login_user_name)
    #print(login_user_name, "NAGOYA INFO")
    #logger.info("%s NAGOYA INFO", login_user_name)
    #imgs = picture_db.objects.get(location = "Nagoya")
    return render(request, "users/Nagoya.html")

def GetTakayama(request):
    logger.info("USER:%s LOAD TAKAYAMA PAGE", login_user_name)
    # print(logger.info("%s TAKAYAMA INFO", login_user_name) +"test")
    imgs = image_db.objects.all()
    print(imgs)
    return render(request, "users/Takayama.html", {"imgs" : imgs})

def GetTakayama_mov(request):
    logger.info("USER:%s LOAD TAKAYAMA_MOV PAGE", login_user_name)
    #imgs = picture_db.objects.get(location = "Toyama")
    return render(request, "users/Takayama_mov.html")

def GetToyama(request):
    logger.info("USER:%s LOAD TOYAMA PAGE", login_user_name)
    #imgs = picture_db.objects.get(location = "Toyama")
    return render(request, "users/Toyama.html")

def GetGero(request):
    logger.info("USER:%s LOAD GERO PAGE", login_user_name)
    #imgs = picture_db.objects.get(location = "Gero")
    return render(request, "users/Gero.html")

def GetBacktoLogin():
    logger.info("USER:%s LOAD NAGOYA PAGE", login_user_name)
    return redirect("user:login")

def GetShirakawago(request):
    logger.info("USER:%s LOAD SHIRAKAWAGO PAGE", login_user_name)
    #imgs = picture_db.objects.get(location = "Gero")
    return render(request, "users/Shirakawago.html")

def Chubu_view(request):
    logger.info("USER:%s LOAD CHUBU PAGE", login_user_name)
    return render(request, "users/Chubu.html")

def Wrong_view(request):  
    logger.info("USER:%s WRONG PAGE", login_user_name)
    msg = 0
    if msg ==0:
        msg +=1
        return render(request,"users/Wrong.html")
        time.sleep(3)
        
    return redirect("user:login")

def choice_view(request):
    logger.info("USER:%s LOAD TAKAYAMA PIC/MOV CHOICE PAGE", login_user_name)
    return render(request, "users/choice.html")

def choice_gero_view(request):
    logger.info("USER:%s LOAD GERO PIC/MOV CHOICE PAGE", login_user_name)
    return render(request, "users/choice_gero.html")

def choice_nagoya_view(request):
    logger.info("USER:%s LOAD NAGOYA PIC/MOV CHOICE PAGE", login_user_name)
    return render(request, "users/choice_nagoya.html")

def choice_toyama_view(request):
    logger.info("USER:%s LOAD TOYAMA PIC/MOV CHOICE PAGE", login_user_name)
    return render(request, "users/choice_toyama.html")

def choice_shirakawago_view(request):
    logger.info("USER:%s LOAD SHIRAKAWAGO PIC/MOV CHOICE PAGE", login_user_name)
    return render(request, "users/choice_shirakawago.html")

users/templates/users/Chubu2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <script>
        function redirectToUrl_toyama() {
            var url = "{% url 'user:choice_toyama' %}";
            window.location.href = url;
        }
        function redirectToUrl_Nagoya() {
            var url = "{% url 'user:choice_nagoya' %}";
            window.location.href = url;
        }
        function redirectToUrl_Takayama() {
            var url = "{% url 'user:choice' %}";
            window.location.href = url;
        }
        function redirectToUrl_Gero() {
            var url = "{% url 'user:choice_gero' %}";
            window.location.href = url;
        }
        function redirectToUrl_Shirikawago() {
            var url = "{% url 'user:choice_shirakawago' %}";
            window.location.href = url;
        }
        </script>
        <div class="container">
        <div class="login-form-map">
        <div id="tooltip">주부지방
            <h1></h1>
    
        
        

        <p><a href="{% url 'user:GetBacktoLogin' %}">뒤로가기</a></p>
        <div style="position: relative;">
            <img src="{% static 'image5.jpg' %}" alt="Background Image" width="500px" style="margin-left: -100px;">
            <img src="{% static 'nagoya_img.png' %}" alt="Top Image" 
            style="position: absolute; top: 390px; left: 110px; z-index: 1; width: 50px"  onclick=redirectToUrl_Nagoya()>
            <img src="{% static 'shirakawago_img.png' %}" alt="Top Image"
             style="position: absolute; top: 220px; left: 120px; z-index: 1 ; width: 50px"  onclick=redirectToUrl_Shirikawago()>
            <img src="{% static 'takayama_img.png' %}" alt="Top Image" 
            style="position: absolute; top: 150px; left: 160px; z-index: 1 ; width: 50px"  onclick=redirectToUrl_Takayama()>
            <img src="{% static 'toyama_img.png' %}" alt="Top Image" 
            style="position: absolute; top: 50px; left: 150px; z-index: 1 ; width: 50px"  onclick=redirectToUrl_toyama()>
            <img src="{% static 'gero_img.png' %}" alt="Top Image"   
            style="position: absolute; top: 300px; left: 90px; z-index: 1 ; width: 50px"  onclick=redirectToUrl_Gero()>
           
        </div>
    </div>
</div>
</div>
        
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>

        <br>

        <br>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


        




        <div>

        <img src="/static/image/image4.jpg" alt="" usemap="#imgmap2023312235654" >
        <map id="imgmap2023312235654" name="imgmap2023312235654">
            <area shape="rect" alt="Toyama"  title="Toyama" coords="494,14,584,84" href="{% url 'user:choice_toyama' %}" target="" />
            <area shape="rect" alt="Takayama" title="Takayama" coords="514,261,599,328" href="{% url 'user:choice' %}" target="" />
            <area shape="rect" alt="Gero" title="Gero" coords="495,419,613,498" href="{% url 'user:choice_gero' %}" target=""  />
            <area shape="rect" alt="Nagoya" title="Nagoya" coords="355,681,499,773" href="{% url 'user:choice_nagoya' %}" target=""  /><!-- Created by Online Image Map Editor (http://www.maschek.hu/imagemap/index) --></map>


    </div>
</body>
</html>

users/templates/users/Gero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gero</title>
</head>
<body>
    <h1>Gero</h1>
    <br>
    <img src="/static/image/Gero2.JPG" alt="" width="300px">
    <p><a href="{% url 'user:choice_gero' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/Shirakawago.html
<!doctype html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <title>CSS</title>
    <style>
      body {
        font-family: Consolas, monospace;
      }
      img {
        max-width: 100%;
      }
      .a {
        width: 200px;
      }
      .a img {
        transition: all 0.2s linear;
      }
      .a:hover img {
        transform: scale(1.4);
      }
      .b {
        width: 200px;
      }
      .b img {
        transition: all 0.2s linear;
      }
      .b:hover img {
        transform: scale(1.4);
      }
      .c {
        width: 200px;
      }
      .c img {
        transition: all 0.2s linear;
      }
      .c:hover img {
        transform: scale(1.4);
      }
      .d {
        width: 200px;
      }
      .d img {
        transition: all 0.2s linear;
      }
      .d:hover img {
        transform: scale(1.4);
      }

      .image-container {
        display: flex;
        flex-wrap: wrap;
      }

      .image-container img {
          width: 200px;
          object-fit: cover;
          transition: transform 0.3s;   
      }

        .image-container img:hover {
          transform: scale(1.4);
      }
    </style>
</head>
<body>
    <h1>시라카와고</h1>
    <div class="a">
        <img src="/static/image/Takayama.JPG" alt="">
    </div>
    <div class="b">
        <img src="/static/image/Takayama2.JPG" alt="">
    </div>


    <div class = "image-container">
        
            <div>
                <img src="/static/image/Shirakawago1.jpeg" alt="">
                <img src="/static/image/Shirakawago2.jpeg" alt="">
                
            </div>
        </p>
        
    </div>


<!--
    <div class="c">
        <img src="http://drive.google.com/uc?export=view&id=1Qf-r6-nED7SqUUhrKiwa5ZNEk_uggRgG" alt="sadfdsaf">
    </div>
    <div class="d">
        <img src="http://drive.google.com/uc?export=view&id=1xm-E8596oYhxu69HGL5PAIix2TYeDbVd" alt="sadfdsaf">
    </div>
-->


    <p><a href="{% url 'user:choice' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/Takayama_mov.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <div class="login-form2">
        <!--<video src="/static/123.mp4" controls width="300"></video>-->
        <video src="https://drive.google.com/uc?export=download&id=1KdL8uDvnhmxgw1TnNLzoPJbo-iypw3yH" controls width="300"></video>
        <!--<iframe src="https://drive.google.com/uc?export=download&id=1MdqDG4YxZQ-8ZhnHwSs2wbY7cwn4qv7Y" width="500" height="600"></iframe>
        <iframe src="https://drive.google.com/uc?export=download&id=1KdL8uDvnhmxgw1TnNLzoPJbo-iypw3yH" width="500" height="600"></iframe>
        <video src="http://naver.me/5t4XeeOn" controls width="300"></video>
        <iframe src="http://naver.me/5t4XeeOn" width="500" height="600"></iframe>-->
    </div>
</head>
<body>
    <p><a href="{% url 'user:choice' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/Toyama.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toyama</title>
</head>
<body>
    <h1>Toyama</h1>
    <br>
    <img src="/static/image/Gero.JPG" alt="" width="300px">
    <p><a href="{% url 'user:choice_toyama' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/Wrong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
         alert('잘못입력했습니다 ')
         setTimeout(function() {
      window.location.href = "login";
    }, 100); // 5000 밀리초 = 5초
    </script>
    
</body>
</html>

users/templates/users/choice.html
choice platform
<!DOCTYPE html>
<html>
<head>
   <title>Image on Image</title>
   <style>
      .container {
         position: relative;
      }
      .chubu-image {
         position: absolute;
         top: 400px;
         left: 100px;
         z-index: 1;
         width: 100px;
      }
      .chugoku-image {
         position: absolute;
         top: 400px;
         left: 400px;
         z-index: 1;
         width: 100px;
      }
   </style>
</head>
    {% load static %}
    <div class="container">
        <img src="{% static 'chubu2.png' %}" alt="Top Image" class="chubu-image"  onclick="location.href='Takayama'">
        <img src="{% static 'chugoku.png' %}" alt="Top Image" class="chugoku-image" onclick="location.href='Takayama_mov'" >
   </div>
   <p><a href="{% url 'user:Chubu' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/choice_gero.html
choice platform
<!DOCTYPE html>
<html>
<head>
   <title>Image on Image</title>
   <style>
      .container {
         position: relative;
      }
      .chubu-image {
         position: absolute;
         top: 400px;
         left: 100px;
         z-index: 1;
         width: 50px;
      }
      .chugoku-image {
         position: absolute;
         top: 400px;
         left: 400px;
         z-index: 1;
         width: 50px;
      }
   </style>
</head>
    {% load static %}
    <div class="container">
        <img src="{% static 'chubu2.png' %}" alt="Top Image" class="chubu-image"  onclick="location.href='Gero'">
        <img src="{% static 'chugoku.png' %}" alt="Top Image" class="chugoku-image" onclick="location.href='Gero'" >
   </div>
   <p><a href="{% url 'user:Chubu' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/choice_nagoya.html
choice platform
<!DOCTYPE html>
<html>
<head>
   <title>Image on Image</title>
   <style>
      .container {
         position: relative;
      }
      .chubu-image {
         position: absolute;
         top: 400px;
         left: 100px;
         z-index: 1;
         width: 100px;
      }
      .chugoku-image {
         position: absolute;
         top: 400px;
         left: 400px;
         z-index: 1;
         width: 100px;
      }
   </style>
</head>
    {% load static %}
    <div class="container">
        <img src="{% static 'chubu2.png' %}" alt="Top Image" class="chubu-image"  onclick="location.href='Nagoya'">
        <img src="{% static 'chugoku.png' %}" alt="Top Image" class="chugoku-image" onclick="location.href='Nagoya'" >
   </div>
   <p><a href="{% url 'user:Chubu' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/choice_shirakawago.html
choice platform
<!DOCTYPE html>
<html>
<head>
   <title>Image on Image</title>
   <style>
      .container {
         position: relative;
      }
      .chubu-image {
         position: absolute;
         top: 400px;
         left: 100px;
         z-index: 1;
         width: 100px;
      }
      .chugoku-image {
         position: absolute;
         top: 400px;
         left: 400px;
         z-index: 1;
         width: 100px;
      }
   </style>
</head>
    {% load static %}
    <div class="container">
        <img src="{% static 'chubu2.png' %}" alt="Top Image" class="chubu-image"  onclick="location.href='Shirakawago'">
        <img src="{% static 'chugoku.png' %}" alt="Top Image" class="chugoku-image" onclick="location.href='Shirakawago'" >
   </div>
   <p><a href="{% url 'user:Chubu' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/choice_toyama.html
choice platform
<!DOCTYPE html>
<html>
<head>
   <title>Image on Image</title>
   <style>
      .container {
         position: relative;
      }
      .chubu-image {
         position: absolute;
         top: 400px;
         left: 100px;
         z-index: 1;
         width: 100px;
      }
      .chugoku-image {
         position: absolute;
         top: 400px;
         left: 400px;
         z-index: 1;
         width: 100px;
      }
   </style>
</head>
    {% load static %}
    <div class="container">
        <img src="{% static 'chubu2.png' %}" alt="Top Image" class="chubu-image"  onclick="location.href='Toyama'">
        <img src="{% static 'chugoku.png' %}" alt="Top Image" class="chugoku-image" onclick="location.href='Toyama'" >
   </div>
   <p><a href="{% url 'user:Chubu' %}">뒤로가기</a></p>
</body>
</html>

users/templates/users/login.html
로그인 페이지
<br>
{% if user.is_authenticated %}
    로그인 성공!
    {{user.username}}님 환영합니다.
    <a href="{% url 'user:logout' %}">로그아웃</a>
    <br>
    <div>
        <img src="users\templates\users\cfile2.uf.250F723C56497F4E0FFA23.jpg" alt="내이미지1" />
        <img src="C:\Users\gog81\Desktop\2023-1\capstone\login-master\login-master\users\templates\users\img.JPG" alt="내이미지2">
        <img src="pngwing.com.png" alt="내이미지3">
        



    </div>
{% else %}

<form action="" method="POST">
    {% csrf_token %}
    <input name="username" type="text">
    <input name="password" type="password">
    <input type="submit" value="로그인">
</form>
<a href="{% url 'user:signup' %}">회원가입</a>


<div>
    
    <!-- <ul class="messages">
     {% for message in messages %}
         {{ message.tag }}
         {{ message }}
     {% endfor %}

    </ul> --> 
    <script>
    var msg = "{{msg}}"
    if(msg =="입력실패" )
    {
      alert(msg)

    }
    </script>
<div>
    
    
 
    	
</div>
</div>


{% endif %}

users/templates/users/login2.html
<!DOCTYPE html>
<html>
<head>
   <title>Image on Image</title>
   <style>
      .container {
         position: relative;
      }

      .chubu-image {
         position: absolute;
         top: 420px;
         left: 290px;
         z-index: 1;
         width: 50px;
      }
      .chugoku-image {
         position: absolute;
         top: 430px;
         left: 160px;
         z-index: 1;
         width: 50px;
      }
      .hokkaido-image {
         position: absolute;
         top: 100px;
         left: 450px;
         z-index: 1;
         width: 50px;
      }
      .kansai-image {
         position: absolute;
         top: 450px;
         left: 220px;
         z-index: 1;
         width: 50px;
      }
      .kyushu-image {
         position: absolute;
         top: 530px;
         left: 90px;
         z-index: 1;
         width: 50px;
      }
      .shigoku-image {
         position: absolute;
         top: 490px;
         left: 160px;
         z-index: 1;
         width: 50px;
      }
      .kanto-image {
         position: absolute;
         top: 400px;
         left: 360px;
         z-index: 1;
         width: 50px;
      }
      .tohoku-image {
         position: absolute;
         top: 300px;
         left: 380px;
         z-index: 1;
         width: 50px;
      }
   </style>
</head>
<body>
    {% load static %}
<link rel="stylesheet" href="{% static 'login.css' %}">
<br>
{% if user.is_authenticated %}
   
    

          <div>
        <div class="container">
         <div class = "login-access">
            로그인 성공!
            {{user.username}}님 환영합니다.
            <br>
            <a href="{% url 'user:logout' %}">로그아웃</a>
         </div>


            <img src="{% static '111.png' %}" alt="Background Image">
            <img src="{% static 'chubu2.png' %}" alt="Top Image" class="chubu-image"  onclick="location.href='Chubu'">
            <img src="{% static 'chugoku.png' %}" alt="Top Image" class="chugoku-image" onclick="location.href='Wrong'" >
            <img src="{% static 'hokkaido.png' %}" alt="Top Image" class="hokkaido-image"  onclick="location.href='Wrong'">
            <img src="{% static 'kansai.png' %}" alt="Top Image" class="kansai-image"  onclick="location.href='Wrong'">
            <img src="{% static 'kyushu.png' %}" alt="Top Image" class="kyushu-image"  onclick="location.href='Wrong'">
            <img src="{% static 'shigoku.png' %}" alt="Top Image" class="shigoku-image"  onclick="location.href='Wrong'">
            <img src="{% static 'tohoku.png' %}" alt="Top Image" class="tohoku-image"  onclick="location.href='Wrong'">
            <img src="{% static 'kanto.png' %}" alt="Top Image" class="kanto-image"  onclick="location.href='Wrong'">
         </div>


{% else %}
<div class = "login-form">
로그인 페이지
<form action="" method="POST">
    {% csrf_token %}
    <input name="username" type="text" placeholder="ID">
    <input name="password" type="password" placeholder="password">
    <input type="submit" value="로그인">
</form>

<div>
    <script>
        var msg = "{{msg}}"
        if(msg =="입력실패" )
        {
          alert(msg)
    
        }
        </script>
<div>
<a href="{% url 'user:signup' %}">회원가입</a>
</div>
{% endif %}
   
</body>
</html>

users/templates/users/test123.html
    
</body>
</html>